updated navbar styles and added home link
civictechdc/civictechdc-website pull request #131
Opened 2024-11-04 18:49 UTC by ChrisDietrich405

This PR introduces a few improvements focused on improving the user experience and accessibility of the site. The changes include:

Logo Size Reduction: Reduced the logo size to improve overall page aesthetics

Added Home Link for Accessibility: Introduced a home link to improve navigation for users relying on screen readers, ensuring better accessibility.

Margin Adjustment for Mobile Hamburger Menu: Added a small margin-right to the hamburger menu on mobile to create better spacing and improve touch usability.

2025-01-18 21:22 UTC, sheldon-b commented
Hey @ChrisDietrich405  -- sorry that I'm just now seeing this PR. I'll add it to my list to review it <3

2025-01-26 20:40 UTC, sheldon-b requested changes
I like the addition of the hero image but I have questions/feedback on the other changes

Can you please merge in latest main, run `npm run lint` to normalize the formatting, and address the comments I made? Thanks!

2025-01-26 20:40 UTC, sheldon-b commented on _includes/core/header.html
> +            <span>Home</span>
I like the addition of the home page to the menu 👍

2025-01-26 20:40 UTC, sheldon-b commented on _includes/core/header.html
> +      <button type="button" id="navbar-hamburger-menu" class="usa-menu-btn">Menu</button>
Can you please explain what the intention here is and how to test it? I checked out this branch and couldn't visually see the 10px right margin. Perhaps a before/after screenshot?

2025-01-26 20:40 UTC, sheldon-b commented on sass/custom/styles.scss
> +    max-height: 4rem;
This makes the too small. I prefer to keep it at 8rem

Perhaps we should align the menu lower with the top of the hero image instead of centered between the top of the screen and the hero image

2026-06-24 18:15 UTC, mikewolfd commented
Closing: superseded and conflicting. A home link was added via aria-label="Home" on the logo, the header has been substantially rebuilt since (15+ commits), and this branch hand-edits assets/css build artifacts which are generated, not hand-edited. Thanks for the contribution.

2026-06-24 18:15 UTC, closed without merging